[package]
name = "transactions_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"
serde = { version = "1", features = ["derive"] }
thiserror = "1.0"
log = "0.4"
env_logger = "0.9.0"